// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ChangedStatsNty : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_9_29(); }
  public static ChangedStatsNty GetRootAsChangedStatsNty(ByteBuffer _bb) { return GetRootAsChangedStatsNty(_bb, new ChangedStatsNty()); }
  public static ChangedStatsNty GetRootAsChangedStatsNty(ByteBuffer _bb, ChangedStatsNty obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ChangedStatsNty __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint ObjId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public int Keys(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int KeysLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetKeysBytes() { return __p.__vector_as_span<int>(6, 4); }
#else
  public ArraySegment<byte>? GetKeysBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public int[] GetKeysArray() { return __p.__vector_as_array<int>(6); }
  public long Values(int j) { int o = __p.__offset(8); return o != 0 ? __p.bb.GetLong(__p.__vector(o) + j * 8) : (long)0; }
  public int ValuesLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<long> GetValuesBytes() { return __p.__vector_as_span<long>(8, 8); }
#else
  public ArraySegment<byte>? GetValuesBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public long[] GetValuesArray() { return __p.__vector_as_array<long>(8); }

  public static Offset<ChangedStatsNty> CreateChangedStatsNty(FlatBufferBuilder builder,
      uint obj_id = 0,
      VectorOffset keysOffset = default(VectorOffset),
      VectorOffset valuesOffset = default(VectorOffset)) {
    builder.StartTable(3);
    ChangedStatsNty.AddValues(builder, valuesOffset);
    ChangedStatsNty.AddKeys(builder, keysOffset);
    ChangedStatsNty.AddObjId(builder, obj_id);
    return ChangedStatsNty.EndChangedStatsNty(builder);
  }

  public static void StartChangedStatsNty(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddObjId(FlatBufferBuilder builder, uint objId) { builder.AddUint(0, objId, 0); }
  public static void AddKeys(FlatBufferBuilder builder, VectorOffset keysOffset) { builder.AddOffset(1, keysOffset.Value, 0); }
  public static VectorOffset CreateKeysVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateKeysVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateKeysVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateKeysVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartKeysVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddValues(FlatBufferBuilder builder, VectorOffset valuesOffset) { builder.AddOffset(2, valuesOffset.Value, 0); }
  public static VectorOffset CreateValuesVector(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); for (int i = data.Length - 1; i >= 0; i--) builder.AddLong(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateValuesVectorBlock(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateValuesVectorBlock(FlatBufferBuilder builder, ArraySegment<long> data) { builder.StartVector(8, data.Count, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateValuesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<long>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartValuesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 8); }
  public static Offset<ChangedStatsNty> EndChangedStatsNty(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ChangedStatsNty>(o);
  }
  public ChangedStatsNtyT UnPack() {
    var _o = new ChangedStatsNtyT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ChangedStatsNtyT _o) {
    _o.ObjId = this.ObjId;
    _o.Keys = new List<int>();
    for (var _j = 0; _j < this.KeysLength; ++_j) {_o.Keys.Add(this.Keys(_j));}
    _o.Values = new List<long>();
    for (var _j = 0; _j < this.ValuesLength; ++_j) {_o.Values.Add(this.Values(_j));}
  }
  public static Offset<ChangedStatsNty> Pack(FlatBufferBuilder builder, ChangedStatsNtyT _o) {
    if (_o == null) return default(Offset<ChangedStatsNty>);
    var _keys = default(VectorOffset);
    if (_o.Keys != null) {
      var __keys = _o.Keys.ToArray();
      _keys = CreateKeysVector(builder, __keys);
    }
    var _values = default(VectorOffset);
    if (_o.Values != null) {
      var __values = _o.Values.ToArray();
      _values = CreateValuesVector(builder, __values);
    }
    return CreateChangedStatsNty(
      builder,
      _o.ObjId,
      _keys,
      _values);
  }
}

public class ChangedStatsNtyT
{
  [Newtonsoft.Json.JsonProperty("obj_id")]
  public uint ObjId { get; set; }
  [Newtonsoft.Json.JsonProperty("keys")]
  public List<int> Keys { get; set; }
  [Newtonsoft.Json.JsonProperty("values")]
  public List<long> Values { get; set; }

  public ChangedStatsNtyT() {
    this.ObjId = 0;
    this.Keys = null;
    this.Values = null;
  }
}

