// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CharacterInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_9_29(); }
  public static CharacterInfo GetRootAsCharacterInfo(ByteBuffer _bb) { return GetRootAsCharacterInfo(_bb, new CharacterInfo()); }
  public static CharacterInfo GetRootAsCharacterInfo(ByteBuffer _bb, CharacterInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CharacterInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong DbId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public int ClassId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Name { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(8); }
  public uint WorldId { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<CharacterInfo> CreateCharacterInfo(FlatBufferBuilder builder,
      ulong db_id = 0,
      int class_id = 0,
      StringOffset nameOffset = default(StringOffset),
      uint world_id = 0) {
    builder.StartTable(4);
    CharacterInfo.AddDbId(builder, db_id);
    CharacterInfo.AddWorldId(builder, world_id);
    CharacterInfo.AddName(builder, nameOffset);
    CharacterInfo.AddClassId(builder, class_id);
    return CharacterInfo.EndCharacterInfo(builder);
  }

  public static void StartCharacterInfo(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddDbId(FlatBufferBuilder builder, ulong dbId) { builder.AddUlong(0, dbId, 0); }
  public static void AddClassId(FlatBufferBuilder builder, int classId) { builder.AddInt(1, classId, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(2, nameOffset.Value, 0); }
  public static void AddWorldId(FlatBufferBuilder builder, uint worldId) { builder.AddUint(3, worldId, 0); }
  public static Offset<CharacterInfo> EndCharacterInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CharacterInfo>(o);
  }
  public CharacterInfoT UnPack() {
    var _o = new CharacterInfoT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CharacterInfoT _o) {
    _o.DbId = this.DbId;
    _o.ClassId = this.ClassId;
    _o.Name = this.Name;
    _o.WorldId = this.WorldId;
  }
  public static Offset<CharacterInfo> Pack(FlatBufferBuilder builder, CharacterInfoT _o) {
    if (_o == null) return default(Offset<CharacterInfo>);
    var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
    return CreateCharacterInfo(
      builder,
      _o.DbId,
      _o.ClassId,
      _name,
      _o.WorldId);
  }
}

public class CharacterInfoT
{
  [Newtonsoft.Json.JsonProperty("db_id")]
  public ulong DbId { get; set; }
  [Newtonsoft.Json.JsonProperty("class_id")]
  public int ClassId { get; set; }
  [Newtonsoft.Json.JsonProperty("name")]
  public string Name { get; set; }
  [Newtonsoft.Json.JsonProperty("world_id")]
  public uint WorldId { get; set; }

  public CharacterInfoT() {
    this.DbId = 0;
    this.ClassId = 0;
    this.Name = null;
    this.WorldId = 0;
  }
}

