// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CreateCharacterReq : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_9_29(); }
  public static CreateCharacterReq GetRootAsCreateCharacterReq(ByteBuffer _bb) { return GetRootAsCreateCharacterReq(_bb, new CreateCharacterReq()); }
  public static CreateCharacterReq GetRootAsCreateCharacterReq(ByteBuffer _bb, CreateCharacterReq obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CreateCharacterReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public int ClassId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<CreateCharacterReq> CreateCreateCharacterReq(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      int class_id = 0) {
    builder.StartTable(2);
    CreateCharacterReq.AddClassId(builder, class_id);
    CreateCharacterReq.AddName(builder, nameOffset);
    return CreateCharacterReq.EndCreateCharacterReq(builder);
  }

  public static void StartCreateCharacterReq(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddClassId(FlatBufferBuilder builder, int classId) { builder.AddInt(1, classId, 0); }
  public static Offset<CreateCharacterReq> EndCreateCharacterReq(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CreateCharacterReq>(o);
  }
  public CreateCharacterReqT UnPack() {
    var _o = new CreateCharacterReqT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CreateCharacterReqT _o) {
    _o.Name = this.Name;
    _o.ClassId = this.ClassId;
  }
  public static Offset<CreateCharacterReq> Pack(FlatBufferBuilder builder, CreateCharacterReqT _o) {
    if (_o == null) return default(Offset<CreateCharacterReq>);
    var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
    return CreateCreateCharacterReq(
      builder,
      _name,
      _o.ClassId);
  }
}

public class CreateCharacterReqT
{
  [Newtonsoft.Json.JsonProperty("name")]
  public string Name { get; set; }
  [Newtonsoft.Json.JsonProperty("class_id")]
  public int ClassId { get; set; }

  public CreateCharacterReqT() {
    this.Name = null;
    this.ClassId = 0;
  }
}

