// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DeadSync : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_9_29(); }
  public static DeadSync GetRootAsDeadSync(ByteBuffer _bb) { return GetRootAsDeadSync(_bb, new DeadSync()); }
  public static DeadSync GetRootAsDeadSync(ByteBuffer _bb, DeadSync obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DeadSync __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint ObjId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<DeadSync> CreateDeadSync(FlatBufferBuilder builder,
      uint obj_id = 0) {
    builder.StartTable(1);
    DeadSync.AddObjId(builder, obj_id);
    return DeadSync.EndDeadSync(builder);
  }

  public static void StartDeadSync(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddObjId(FlatBufferBuilder builder, uint objId) { builder.AddUint(0, objId, 0); }
  public static Offset<DeadSync> EndDeadSync(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<DeadSync>(o);
  }
  public DeadSyncT UnPack() {
    var _o = new DeadSyncT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(DeadSyncT _o) {
    _o.ObjId = this.ObjId;
  }
  public static Offset<DeadSync> Pack(FlatBufferBuilder builder, DeadSyncT _o) {
    if (_o == null) return default(Offset<DeadSync>);
    return CreateDeadSync(
      builder,
      _o.ObjId);
  }
}

public class DeadSyncT
{
  [Newtonsoft.Json.JsonProperty("obj_id")]
  public uint ObjId { get; set; }

  public DeadSyncT() {
    this.ObjId = 0;
  }
}

