// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EnterServerResp : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_9_29(); }
  public static EnterServerResp GetRootAsEnterServerResp(ByteBuffer _bb) { return GetRootAsEnterServerResp(_bb, new EnterServerResp()); }
  public static EnterServerResp GetRootAsEnterServerResp(ByteBuffer _bb, EnterServerResp obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EnterServerResp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ErrorCode ErrorCode { get { int o = __p.__offset(4); return o != 0 ? (ErrorCode)__p.bb.GetShort(o + __p.bb_pos) : ErrorCode.Success; } }
  public CharacterInfo? CharList(int j) { int o = __p.__offset(6); return o != 0 ? (CharacterInfo?)(new CharacterInfo()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int CharListLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public StateSync? Stats(int j) { int o = __p.__offset(8); return o != 0 ? (StateSync?)(new StateSync()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int StatsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<EnterServerResp> CreateEnterServerResp(FlatBufferBuilder builder,
      ErrorCode error_code = ErrorCode.Success,
      VectorOffset char_listOffset = default(VectorOffset),
      VectorOffset statsOffset = default(VectorOffset)) {
    builder.StartTable(3);
    EnterServerResp.AddStats(builder, statsOffset);
    EnterServerResp.AddCharList(builder, char_listOffset);
    EnterServerResp.AddErrorCode(builder, error_code);
    return EnterServerResp.EndEnterServerResp(builder);
  }

  public static void StartEnterServerResp(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddErrorCode(FlatBufferBuilder builder, ErrorCode errorCode) { builder.AddShort(0, (short)errorCode, 0); }
  public static void AddCharList(FlatBufferBuilder builder, VectorOffset charListOffset) { builder.AddOffset(1, charListOffset.Value, 0); }
  public static VectorOffset CreateCharListVector(FlatBufferBuilder builder, Offset<CharacterInfo>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateCharListVectorBlock(FlatBufferBuilder builder, Offset<CharacterInfo>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCharListVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<CharacterInfo>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCharListVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<CharacterInfo>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartCharListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddStats(FlatBufferBuilder builder, VectorOffset statsOffset) { builder.AddOffset(2, statsOffset.Value, 0); }
  public static VectorOffset CreateStatsVector(FlatBufferBuilder builder, Offset<StateSync>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateStatsVectorBlock(FlatBufferBuilder builder, Offset<StateSync>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateStatsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<StateSync>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateStatsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<StateSync>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartStatsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<EnterServerResp> EndEnterServerResp(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<EnterServerResp>(o);
  }
  public EnterServerRespT UnPack() {
    var _o = new EnterServerRespT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(EnterServerRespT _o) {
    _o.ErrorCode = this.ErrorCode;
    _o.CharList = new List<CharacterInfoT>();
    for (var _j = 0; _j < this.CharListLength; ++_j) {_o.CharList.Add(this.CharList(_j).HasValue ? this.CharList(_j).Value.UnPack() : null);}
    _o.Stats = new List<StateSyncT>();
    for (var _j = 0; _j < this.StatsLength; ++_j) {_o.Stats.Add(this.Stats(_j).HasValue ? this.Stats(_j).Value.UnPack() : null);}
  }
  public static Offset<EnterServerResp> Pack(FlatBufferBuilder builder, EnterServerRespT _o) {
    if (_o == null) return default(Offset<EnterServerResp>);
    var _char_list = default(VectorOffset);
    if (_o.CharList != null) {
      var __char_list = new Offset<CharacterInfo>[_o.CharList.Count];
      for (var _j = 0; _j < __char_list.Length; ++_j) { __char_list[_j] = CharacterInfo.Pack(builder, _o.CharList[_j]); }
      _char_list = CreateCharListVector(builder, __char_list);
    }
    var _stats = default(VectorOffset);
    if (_o.Stats != null) {
      var __stats = new Offset<StateSync>[_o.Stats.Count];
      for (var _j = 0; _j < __stats.Length; ++_j) { __stats[_j] = StateSync.Pack(builder, _o.Stats[_j]); }
      _stats = CreateStatsVector(builder, __stats);
    }
    return CreateEnterServerResp(
      builder,
      _o.ErrorCode,
      _char_list,
      _stats);
  }
}

public class EnterServerRespT
{
  [Newtonsoft.Json.JsonProperty("error_code")]
  public ErrorCode ErrorCode { get; set; }
  [Newtonsoft.Json.JsonProperty("char_list")]
  public List<CharacterInfoT> CharList { get; set; }
  [Newtonsoft.Json.JsonProperty("stats")]
  public List<StateSyncT> Stats { get; set; }

  public EnterServerRespT() {
    this.ErrorCode = ErrorCode.Success;
    this.CharList = null;
    this.Stats = null;
  }
}

