// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EnterWorldReq : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_9_29(); }
  public static EnterWorldReq GetRootAsEnterWorldReq(ByteBuffer _bb) { return GetRootAsEnterWorldReq(_bb, new EnterWorldReq()); }
  public static EnterWorldReq GetRootAsEnterWorldReq(ByteBuffer _bb, EnterWorldReq obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EnterWorldReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint WorldId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<EnterWorldReq> CreateEnterWorldReq(FlatBufferBuilder builder,
      uint world_id = 0) {
    builder.StartTable(1);
    EnterWorldReq.AddWorldId(builder, world_id);
    return EnterWorldReq.EndEnterWorldReq(builder);
  }

  public static void StartEnterWorldReq(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddWorldId(FlatBufferBuilder builder, uint worldId) { builder.AddUint(0, worldId, 0); }
  public static Offset<EnterWorldReq> EndEnterWorldReq(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<EnterWorldReq>(o);
  }
  public EnterWorldReqT UnPack() {
    var _o = new EnterWorldReqT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(EnterWorldReqT _o) {
    _o.WorldId = this.WorldId;
  }
  public static Offset<EnterWorldReq> Pack(FlatBufferBuilder builder, EnterWorldReqT _o) {
    if (_o == null) return default(Offset<EnterWorldReq>);
    return CreateEnterWorldReq(
      builder,
      _o.WorldId);
  }
}

public class EnterWorldReqT
{
  [Newtonsoft.Json.JsonProperty("world_id")]
  public uint WorldId { get; set; }

  public EnterWorldReqT() {
    this.WorldId = 0;
  }
}

