// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EnterLobbyReq : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_9_29(); }
  public static EnterLobbyReq GetRootAsEnterLobbyReq(ByteBuffer _bb) { return GetRootAsEnterLobbyReq(_bb, new EnterLobbyReq()); }
  public static EnterLobbyReq GetRootAsEnterLobbyReq(ByteBuffer _bb, EnterLobbyReq obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EnterLobbyReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartEnterLobbyReq(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<EnterLobbyReq> EndEnterLobbyReq(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<EnterLobbyReq>(o);
  }
  public EnterLobbyReqT UnPack() {
    var _o = new EnterLobbyReqT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(EnterLobbyReqT _o) {
  }
  public static Offset<EnterLobbyReq> Pack(FlatBufferBuilder builder, EnterLobbyReqT _o) {
    if (_o == null) return default(Offset<EnterLobbyReq>);
    StartEnterLobbyReq(builder);
    return EndEnterLobbyReq(builder);
  }
}

public class EnterLobbyReqT
{

  public EnterLobbyReqT() {
  }
}

