// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

[Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
public enum ErrorCode : short
{
  UndefinedError = -1,
  Success = 0,
  SessionError = 1,
  PacketDataError = 2,
  DuplicatedError = 3,
  DatabaseError = 4,
  NotExistsError = 5,
  AlreadyInProcess = 6,
  WorldSyncError = 7,
};

