// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MoveSceneReq : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_9_29(); }
  public static MoveSceneReq GetRootAsMoveSceneReq(ByteBuffer _bb) { return GetRootAsMoveSceneReq(_bb, new MoveSceneReq()); }
  public static MoveSceneReq GetRootAsMoveSceneReq(ByteBuffer _bb, MoveSceneReq obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MoveSceneReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint WorldId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<MoveSceneReq> CreateMoveSceneReq(FlatBufferBuilder builder,
      uint world_id = 0) {
    builder.StartTable(1);
    MoveSceneReq.AddWorldId(builder, world_id);
    return MoveSceneReq.EndMoveSceneReq(builder);
  }

  public static void StartMoveSceneReq(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddWorldId(FlatBufferBuilder builder, uint worldId) { builder.AddUint(0, worldId, 0); }
  public static Offset<MoveSceneReq> EndMoveSceneReq(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MoveSceneReq>(o);
  }
  public MoveSceneReqT UnPack() {
    var _o = new MoveSceneReqT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(MoveSceneReqT _o) {
    _o.WorldId = this.WorldId;
  }
  public static Offset<MoveSceneReq> Pack(FlatBufferBuilder builder, MoveSceneReqT _o) {
    if (_o == null) return default(Offset<MoveSceneReq>);
    return CreateMoveSceneReq(
      builder,
      _o.WorldId);
  }
}

public class MoveSceneReqT
{
  [Newtonsoft.Json.JsonProperty("world_id")]
  public uint WorldId { get; set; }

  public MoveSceneReqT() {
    this.WorldId = 0;
  }
}

