// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MoveSceneResp : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_9_29(); }
  public static MoveSceneResp GetRootAsMoveSceneResp(ByteBuffer _bb) { return GetRootAsMoveSceneResp(_bb, new MoveSceneResp()); }
  public static MoveSceneResp GetRootAsMoveSceneResp(ByteBuffer _bb, MoveSceneResp obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MoveSceneResp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint WorldId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public ErrorCode ErrorCode { get { int o = __p.__offset(6); return o != 0 ? (ErrorCode)__p.bb.GetShort(o + __p.bb_pos) : ErrorCode.Success; } }

  public static Offset<MoveSceneResp> CreateMoveSceneResp(FlatBufferBuilder builder,
      uint world_id = 0,
      ErrorCode error_code = ErrorCode.Success) {
    builder.StartTable(2);
    MoveSceneResp.AddWorldId(builder, world_id);
    MoveSceneResp.AddErrorCode(builder, error_code);
    return MoveSceneResp.EndMoveSceneResp(builder);
  }

  public static void StartMoveSceneResp(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddWorldId(FlatBufferBuilder builder, uint worldId) { builder.AddUint(0, worldId, 0); }
  public static void AddErrorCode(FlatBufferBuilder builder, ErrorCode errorCode) { builder.AddShort(1, (short)errorCode, 0); }
  public static Offset<MoveSceneResp> EndMoveSceneResp(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MoveSceneResp>(o);
  }
  public MoveSceneRespT UnPack() {
    var _o = new MoveSceneRespT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(MoveSceneRespT _o) {
    _o.WorldId = this.WorldId;
    _o.ErrorCode = this.ErrorCode;
  }
  public static Offset<MoveSceneResp> Pack(FlatBufferBuilder builder, MoveSceneRespT _o) {
    if (_o == null) return default(Offset<MoveSceneResp>);
    return CreateMoveSceneResp(
      builder,
      _o.WorldId,
      _o.ErrorCode);
  }
}

public class MoveSceneRespT
{
  [Newtonsoft.Json.JsonProperty("world_id")]
  public uint WorldId { get; set; }
  [Newtonsoft.Json.JsonProperty("error_code")]
  public ErrorCode ErrorCode { get; set; }

  public MoveSceneRespT() {
    this.WorldId = 0;
    this.ErrorCode = ErrorCode.Success;
  }
}

