// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

[Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
public enum SyncVar64 : byte
{
  Hp = 0,
  MaxHp = 1,
  Damage = 2,
  Gold = 3,
  Exp = 4,
  End = 5,
};

