// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct TradeAcceptResp : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_9_29(); }
  public static TradeAcceptResp GetRootAsTradeAcceptResp(ByteBuffer _bb) { return GetRootAsTradeAcceptResp(_bb, new TradeAcceptResp()); }
  public static TradeAcceptResp GetRootAsTradeAcceptResp(ByteBuffer _bb, TradeAcceptResp obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TradeAcceptResp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint TradeId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public bool Agreement { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<TradeAcceptResp> CreateTradeAcceptResp(FlatBufferBuilder builder,
      uint trade_id = 0,
      bool agreement = false) {
    builder.StartTable(2);
    TradeAcceptResp.AddTradeId(builder, trade_id);
    TradeAcceptResp.AddAgreement(builder, agreement);
    return TradeAcceptResp.EndTradeAcceptResp(builder);
  }

  public static void StartTradeAcceptResp(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddTradeId(FlatBufferBuilder builder, uint tradeId) { builder.AddUint(0, tradeId, 0); }
  public static void AddAgreement(FlatBufferBuilder builder, bool agreement) { builder.AddBool(1, agreement, false); }
  public static Offset<TradeAcceptResp> EndTradeAcceptResp(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<TradeAcceptResp>(o);
  }
  public TradeAcceptRespT UnPack() {
    var _o = new TradeAcceptRespT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(TradeAcceptRespT _o) {
    _o.TradeId = this.TradeId;
    _o.Agreement = this.Agreement;
  }
  public static Offset<TradeAcceptResp> Pack(FlatBufferBuilder builder, TradeAcceptRespT _o) {
    if (_o == null) return default(Offset<TradeAcceptResp>);
    return CreateTradeAcceptResp(
      builder,
      _o.TradeId,
      _o.Agreement);
  }
}

public class TradeAcceptRespT
{
  [Newtonsoft.Json.JsonProperty("trade_id")]
  public uint TradeId { get; set; }
  [Newtonsoft.Json.JsonProperty("agreement")]
  public bool Agreement { get; set; }

  public TradeAcceptRespT() {
    this.TradeId = 0;
    this.Agreement = false;
  }
}

