// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct TradeCancelSync : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_9_29(); }
  public static TradeCancelSync GetRootAsTradeCancelSync(ByteBuffer _bb) { return GetRootAsTradeCancelSync(_bb, new TradeCancelSync()); }
  public static TradeCancelSync GetRootAsTradeCancelSync(ByteBuffer _bb, TradeCancelSync obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TradeCancelSync __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint TradeId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<TradeCancelSync> CreateTradeCancelSync(FlatBufferBuilder builder,
      uint trade_id = 0) {
    builder.StartTable(1);
    TradeCancelSync.AddTradeId(builder, trade_id);
    return TradeCancelSync.EndTradeCancelSync(builder);
  }

  public static void StartTradeCancelSync(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTradeId(FlatBufferBuilder builder, uint tradeId) { builder.AddUint(0, tradeId, 0); }
  public static Offset<TradeCancelSync> EndTradeCancelSync(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<TradeCancelSync>(o);
  }
  public TradeCancelSyncT UnPack() {
    var _o = new TradeCancelSyncT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(TradeCancelSyncT _o) {
    _o.TradeId = this.TradeId;
  }
  public static Offset<TradeCancelSync> Pack(FlatBufferBuilder builder, TradeCancelSyncT _o) {
    if (_o == null) return default(Offset<TradeCancelSync>);
    return CreateTradeCancelSync(
      builder,
      _o.TradeId);
  }
}

public class TradeCancelSyncT
{
  [Newtonsoft.Json.JsonProperty("trade_id")]
  public uint TradeId { get; set; }

  public TradeCancelSyncT() {
    this.TradeId = 0;
  }
}

