// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct TradeBeginSync : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_9_29(); }
  public static TradeBeginSync GetRootAsTradeBeginSync(ByteBuffer _bb) { return GetRootAsTradeBeginSync(_bb, new TradeBeginSync()); }
  public static TradeBeginSync GetRootAsTradeBeginSync(ByteBuffer _bb, TradeBeginSync obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TradeBeginSync __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint TradeId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<TradeBeginSync> CreateTradeBeginSync(FlatBufferBuilder builder,
      uint trade_id = 0) {
    builder.StartTable(1);
    TradeBeginSync.AddTradeId(builder, trade_id);
    return TradeBeginSync.EndTradeBeginSync(builder);
  }

  public static void StartTradeBeginSync(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTradeId(FlatBufferBuilder builder, uint tradeId) { builder.AddUint(0, tradeId, 0); }
  public static Offset<TradeBeginSync> EndTradeBeginSync(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<TradeBeginSync>(o);
  }
  public TradeBeginSyncT UnPack() {
    var _o = new TradeBeginSyncT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(TradeBeginSyncT _o) {
    _o.TradeId = this.TradeId;
  }
  public static Offset<TradeBeginSync> Pack(FlatBufferBuilder builder, TradeBeginSyncT _o) {
    if (_o == null) return default(Offset<TradeBeginSync>);
    return CreateTradeBeginSync(
      builder,
      _o.TradeId);
  }
}

public class TradeBeginSyncT
{
  [Newtonsoft.Json.JsonProperty("trade_id")]
  public uint TradeId { get; set; }

  public TradeBeginSyncT() {
    this.TradeId = 0;
  }
}

