// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct TradeCancelReq : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_9_29(); }
  public static TradeCancelReq GetRootAsTradeCancelReq(ByteBuffer _bb) { return GetRootAsTradeCancelReq(_bb, new TradeCancelReq()); }
  public static TradeCancelReq GetRootAsTradeCancelReq(ByteBuffer _bb, TradeCancelReq obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TradeCancelReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint TradeId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<TradeCancelReq> CreateTradeCancelReq(FlatBufferBuilder builder,
      uint trade_id = 0) {
    builder.StartTable(1);
    TradeCancelReq.AddTradeId(builder, trade_id);
    return TradeCancelReq.EndTradeCancelReq(builder);
  }

  public static void StartTradeCancelReq(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTradeId(FlatBufferBuilder builder, uint tradeId) { builder.AddUint(0, tradeId, 0); }
  public static Offset<TradeCancelReq> EndTradeCancelReq(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<TradeCancelReq>(o);
  }
  public TradeCancelReqT UnPack() {
    var _o = new TradeCancelReqT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(TradeCancelReqT _o) {
    _o.TradeId = this.TradeId;
  }
  public static Offset<TradeCancelReq> Pack(FlatBufferBuilder builder, TradeCancelReqT _o) {
    if (_o == null) return default(Offset<TradeCancelReq>);
    return CreateTradeCancelReq(
      builder,
      _o.TradeId);
  }
}

public class TradeCancelReqT
{
  [Newtonsoft.Json.JsonProperty("trade_id")]
  public uint TradeId { get; set; }

  public TradeCancelReqT() {
    this.TradeId = 0;
  }
}

