// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct TradeRequestReq : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_9_29(); }
  public static TradeRequestReq GetRootAsTradeRequestReq(ByteBuffer _bb) { return GetRootAsTradeRequestReq(_bb, new TradeRequestReq()); }
  public static TradeRequestReq GetRootAsTradeRequestReq(ByteBuffer _bb, TradeRequestReq obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TradeRequestReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint ObjId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<TradeRequestReq> CreateTradeRequestReq(FlatBufferBuilder builder,
      uint obj_id = 0) {
    builder.StartTable(1);
    TradeRequestReq.AddObjId(builder, obj_id);
    return TradeRequestReq.EndTradeRequestReq(builder);
  }

  public static void StartTradeRequestReq(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddObjId(FlatBufferBuilder builder, uint objId) { builder.AddUint(0, objId, 0); }
  public static Offset<TradeRequestReq> EndTradeRequestReq(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<TradeRequestReq>(o);
  }
  public TradeRequestReqT UnPack() {
    var _o = new TradeRequestReqT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(TradeRequestReqT _o) {
    _o.ObjId = this.ObjId;
  }
  public static Offset<TradeRequestReq> Pack(FlatBufferBuilder builder, TradeRequestReqT _o) {
    if (_o == null) return default(Offset<TradeRequestReq>);
    return CreateTradeRequestReq(
      builder,
      _o.ObjId);
  }
}

public class TradeRequestReqT
{
  [Newtonsoft.Json.JsonProperty("obj_id")]
  public uint ObjId { get; set; }

  public TradeRequestReqT() {
    this.ObjId = 0;
  }
}

